---
- include: "os/{{ ansible_os_family }}.yml"

- name: ensure config folder is present
  file: path=/etc/docker state=directory

- name: ensure daemon config file is present
  template: src=daemon.j2.json dest=/etc/docker/daemon.json
  notify:
    - restart docker

- name: ensure unit file is present & up to date
  copy: src=files/docker.service dest=/usr/lib/systemd/system/docker.service
  notify:
    - reload unit
    - restart docker

- meta: flush_handlers

- name: ensure starts on system boot
  service: name=docker enabled=yes
